name: Test Github Actions

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - name: Checkout repository
      - uses: actions/checkout@v4

      - name: Install node
      - uses: actions/setup-node@v4

      - name: Install dependencies
      - run: npm run setup:local

      - name: Run setup:all
      - run: npm run setup:all
      
      - name: Start project
      - run: npm run start

