name: Test Github Actions

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm run setup:local

      - name: Run setup:all
        run: npm run setup:all

      - name: Start project
        run: npm run start

